version: '3.8'
services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:qWfUxFeMrtQxRtpHakAkVIWMxNsVGpLc@shinkansen.proxy.rlwy.net:52381
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - my_network  

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - my_network 
      
networks:
  my_network:
    driver: bridge
