version: '3.8'
services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:rootpassword@mongo:27017/teste_hub_xp?authSource=admin
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
